// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.1
// 	protoc        v5.26.1
// source: internal/proto/anniedad/anniedad.proto

package anniedad

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MediaStatus int32

const (
	MediaStatus_MEDIA_OK      MediaStatus = 0
	MediaStatus_MEDIA_ERROR   MediaStatus = 1
	MediaStatus_MEDIA_SKIPPED MediaStatus = 2
)

// Enum value maps for MediaStatus.
var (
	MediaStatus_name = map[int32]string{
		0: "MEDIA_OK",
		1: "MEDIA_ERROR",
		2: "MEDIA_SKIPPED",
	}
	MediaStatus_value = map[string]int32{
		"MEDIA_OK":      0,
		"MEDIA_ERROR":   1,
		"MEDIA_SKIPPED": 2,
	}
)

func (x MediaStatus) Enum() *MediaStatus {
	p := new(MediaStatus)
	*p = x
	return p
}

func (x MediaStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MediaStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_internal_proto_anniedad_anniedad_proto_enumTypes[0].Descriptor()
}

func (MediaStatus) Type() protoreflect.EnumType {
	return &file_internal_proto_anniedad_anniedad_proto_enumTypes[0]
}

func (x MediaStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MediaStatus.Descriptor instead.
func (MediaStatus) EnumDescriptor() ([]byte, []int) {
	return file_internal_proto_anniedad_anniedad_proto_rawDescGZIP(), []int{0}
}

type PostMediaRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data []*PostMediaRequestMessage `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty"`
}

func (x *PostMediaRequest) Reset() {
	*x = PostMediaRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_proto_anniedad_anniedad_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PostMediaRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PostMediaRequest) ProtoMessage() {}

func (x *PostMediaRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_anniedad_anniedad_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PostMediaRequest.ProtoReflect.Descriptor instead.
func (*PostMediaRequest) Descriptor() ([]byte, []int) {
	return file_internal_proto_anniedad_anniedad_proto_rawDescGZIP(), []int{0}
}

func (x *PostMediaRequest) GetData() []*PostMediaRequestMessage {
	if x != nil {
		return x.Data
	}
	return nil
}

type PostMediaRequestMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Filename  string           `protobuf:"bytes,1,opt,name=filename,proto3" json:"filename,omitempty"`
	MimeType  string           `protobuf:"bytes,2,opt,name=mime_type,json=mimeType,proto3" json:"mime_type,omitempty"`     // optional
	SizeBytes int64            `protobuf:"varint,3,opt,name=size_bytes,json=sizeBytes,proto3" json:"size_bytes,omitempty"` // optional
	Meta      *structpb.Struct `protobuf:"bytes,4,opt,name=meta,proto3" json:"meta,omitempty"`                             // optional
}

func (x *PostMediaRequestMessage) Reset() {
	*x = PostMediaRequestMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_proto_anniedad_anniedad_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PostMediaRequestMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PostMediaRequestMessage) ProtoMessage() {}

func (x *PostMediaRequestMessage) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_anniedad_anniedad_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PostMediaRequestMessage.ProtoReflect.Descriptor instead.
func (*PostMediaRequestMessage) Descriptor() ([]byte, []int) {
	return file_internal_proto_anniedad_anniedad_proto_rawDescGZIP(), []int{1}
}

func (x *PostMediaRequestMessage) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

func (x *PostMediaRequestMessage) GetMimeType() string {
	if x != nil {
		return x.MimeType
	}
	return ""
}

func (x *PostMediaRequestMessage) GetSizeBytes() int64 {
	if x != nil {
		return x.SizeBytes
	}
	return 0
}

func (x *PostMediaRequestMessage) GetMeta() *structpb.Struct {
	if x != nil {
		return x.Meta
	}
	return nil
}

type PostMediaResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data []*PostMediaResponseMessage `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty"`
}

func (x *PostMediaResponse) Reset() {
	*x = PostMediaResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_proto_anniedad_anniedad_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PostMediaResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PostMediaResponse) ProtoMessage() {}

func (x *PostMediaResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_anniedad_anniedad_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PostMediaResponse.ProtoReflect.Descriptor instead.
func (*PostMediaResponse) Descriptor() ([]byte, []int) {
	return file_internal_proto_anniedad_anniedad_proto_rawDescGZIP(), []int{2}
}

func (x *PostMediaResponse) GetData() []*PostMediaResponseMessage {
	if x != nil {
		return x.Data
	}
	return nil
}

type PostMediaResponseMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	FileId       string      `protobuf:"bytes,1,opt,name=file_id,json=fileId,proto3" json:"file_id,omitempty"`
	Filename     string      `protobuf:"bytes,2,opt,name=filename,proto3" json:"filename,omitempty"`
	UploadUrl    string      `protobuf:"bytes,3,opt,name=upload_url,json=uploadUrl,proto3" json:"upload_url,omitempty"`
	StoragePath  string      `protobuf:"bytes,4,opt,name=storage_path,json=storagePath,proto3" json:"storage_path,omitempty"`
	Status       MediaStatus `protobuf:"varint,5,opt,name=status,proto3,enum=main.MediaStatus" json:"status,omitempty"`
	ErrorMessage string      `protobuf:"bytes,6,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
}

func (x *PostMediaResponseMessage) Reset() {
	*x = PostMediaResponseMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_proto_anniedad_anniedad_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PostMediaResponseMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PostMediaResponseMessage) ProtoMessage() {}

func (x *PostMediaResponseMessage) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_anniedad_anniedad_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PostMediaResponseMessage.ProtoReflect.Descriptor instead.
func (*PostMediaResponseMessage) Descriptor() ([]byte, []int) {
	return file_internal_proto_anniedad_anniedad_proto_rawDescGZIP(), []int{3}
}

func (x *PostMediaResponseMessage) GetFileId() string {
	if x != nil {
		return x.FileId
	}
	return ""
}

func (x *PostMediaResponseMessage) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

func (x *PostMediaResponseMessage) GetUploadUrl() string {
	if x != nil {
		return x.UploadUrl
	}
	return ""
}

func (x *PostMediaResponseMessage) GetStoragePath() string {
	if x != nil {
		return x.StoragePath
	}
	return ""
}

func (x *PostMediaResponseMessage) GetStatus() MediaStatus {
	if x != nil {
		return x.Status
	}
	return MediaStatus_MEDIA_OK
}

func (x *PostMediaResponseMessage) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

type GetMediaRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data []*GetMediaRequestMessage `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty"`
}

func (x *GetMediaRequest) Reset() {
	*x = GetMediaRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_proto_anniedad_anniedad_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetMediaRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMediaRequest) ProtoMessage() {}

func (x *GetMediaRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_anniedad_anniedad_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMediaRequest.ProtoReflect.Descriptor instead.
func (*GetMediaRequest) Descriptor() ([]byte, []int) {
	return file_internal_proto_anniedad_anniedad_proto_rawDescGZIP(), []int{4}
}

func (x *GetMediaRequest) GetData() []*GetMediaRequestMessage {
	if x != nil {
		return x.Data
	}
	return nil
}

type GetMediaRequestMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	FileId string `protobuf:"bytes,1,opt,name=file_id,json=fileId,proto3" json:"file_id,omitempty"`
}

func (x *GetMediaRequestMessage) Reset() {
	*x = GetMediaRequestMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_proto_anniedad_anniedad_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetMediaRequestMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMediaRequestMessage) ProtoMessage() {}

func (x *GetMediaRequestMessage) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_anniedad_anniedad_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMediaRequestMessage.ProtoReflect.Descriptor instead.
func (*GetMediaRequestMessage) Descriptor() ([]byte, []int) {
	return file_internal_proto_anniedad_anniedad_proto_rawDescGZIP(), []int{5}
}

func (x *GetMediaRequestMessage) GetFileId() string {
	if x != nil {
		return x.FileId
	}
	return ""
}

type GetMediaResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data []*GetMediaResponseMessage `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty"`
}

func (x *GetMediaResponse) Reset() {
	*x = GetMediaResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_proto_anniedad_anniedad_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetMediaResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMediaResponse) ProtoMessage() {}

func (x *GetMediaResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_anniedad_anniedad_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMediaResponse.ProtoReflect.Descriptor instead.
func (*GetMediaResponse) Descriptor() ([]byte, []int) {
	return file_internal_proto_anniedad_anniedad_proto_rawDescGZIP(), []int{6}
}

func (x *GetMediaResponse) GetData() []*GetMediaResponseMessage {
	if x != nil {
		return x.Data
	}
	return nil
}

type GetMediaResponseMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	DownloadUrl  string           `protobuf:"bytes,1,opt,name=download_url,json=downloadUrl,proto3" json:"download_url,omitempty"`
	FileId       string           `protobuf:"bytes,2,opt,name=file_id,json=fileId,proto3" json:"file_id,omitempty"`
	Filename     string           `protobuf:"bytes,3,opt,name=filename,proto3" json:"filename,omitempty"`
	MimeType     string           `protobuf:"bytes,4,opt,name=mime_type,json=mimeType,proto3" json:"mime_type,omitempty"`
	SizeBytes    int64            `protobuf:"varint,5,opt,name=size_bytes,json=sizeBytes,proto3" json:"size_bytes,omitempty"`
	UploadedAt   string           `protobuf:"bytes,6,opt,name=uploaded_at,json=uploadedAt,proto3" json:"uploaded_at,omitempty"`
	Meta         *structpb.Struct `protobuf:"bytes,7,opt,name=meta,proto3" json:"meta,omitempty"`
	ErrorMessage string           `protobuf:"bytes,8,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
}

func (x *GetMediaResponseMessage) Reset() {
	*x = GetMediaResponseMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_proto_anniedad_anniedad_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetMediaResponseMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMediaResponseMessage) ProtoMessage() {}

func (x *GetMediaResponseMessage) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_anniedad_anniedad_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMediaResponseMessage.ProtoReflect.Descriptor instead.
func (*GetMediaResponseMessage) Descriptor() ([]byte, []int) {
	return file_internal_proto_anniedad_anniedad_proto_rawDescGZIP(), []int{7}
}

func (x *GetMediaResponseMessage) GetDownloadUrl() string {
	if x != nil {
		return x.DownloadUrl
	}
	return ""
}

func (x *GetMediaResponseMessage) GetFileId() string {
	if x != nil {
		return x.FileId
	}
	return ""
}

func (x *GetMediaResponseMessage) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

func (x *GetMediaResponseMessage) GetMimeType() string {
	if x != nil {
		return x.MimeType
	}
	return ""
}

func (x *GetMediaResponseMessage) GetSizeBytes() int64 {
	if x != nil {
		return x.SizeBytes
	}
	return 0
}

func (x *GetMediaResponseMessage) GetUploadedAt() string {
	if x != nil {
		return x.UploadedAt
	}
	return ""
}

func (x *GetMediaResponseMessage) GetMeta() *structpb.Struct {
	if x != nil {
		return x.Meta
	}
	return nil
}

func (x *GetMediaResponseMessage) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

var File_internal_proto_anniedad_anniedad_proto protoreflect.FileDescriptor

var file_internal_proto_anniedad_anniedad_proto_rawDesc = []byte{
	0x0a, 0x26, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x2f, 0x61, 0x6e, 0x6e, 0x69, 0x65, 0x64, 0x61, 0x64, 0x2f, 0x61, 0x6e, 0x6e, 0x69, 0x65, 0x64,
	0x61, 0x64, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x04, 0x6d, 0x61, 0x69, 0x6e, 0x1a, 0x1c,
	0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f,
	0x73, 0x74, 0x72, 0x75, 0x63, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x45, 0x0a, 0x10,
	0x50, 0x6f, 0x73, 0x74, 0x4d, 0x65, 0x64, 0x69, 0x61, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x31, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1d,
	0x2e, 0x6d, 0x61, 0x69, 0x6e, 0x2e, 0x50, 0x6f, 0x73, 0x74, 0x4d, 0x65, 0x64, 0x69, 0x61, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x52, 0x04, 0x64,
	0x61, 0x74, 0x61, 0x22, 0x9e, 0x01, 0x0a, 0x17, 0x50, 0x6f, 0x73, 0x74, 0x4d, 0x65, 0x64, 0x69,
	0x61, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12,
	0x1a, 0x0a, 0x08, 0x66, 0x69, 0x6c, 0x65, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x08, 0x66, 0x69, 0x6c, 0x65, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x1b, 0x0a, 0x09, 0x6d,
	0x69, 0x6d, 0x65, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08,
	0x6d, 0x69, 0x6d, 0x65, 0x54, 0x79, 0x70, 0x65, 0x12, 0x1d, 0x0a, 0x0a, 0x73, 0x69, 0x7a, 0x65,
	0x5f, 0x62, 0x79, 0x74, 0x65, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x73, 0x69,
	0x7a, 0x65, 0x42, 0x79, 0x74, 0x65, 0x73, 0x12, 0x2b, 0x0a, 0x04, 0x6d, 0x65, 0x74, 0x61, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x53, 0x74, 0x72, 0x75, 0x63, 0x74, 0x52, 0x04,
	0x6d, 0x65, 0x74, 0x61, 0x22, 0x47, 0x0a, 0x11, 0x50, 0x6f, 0x73, 0x74, 0x4d, 0x65, 0x64, 0x69,
	0x61, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x32, 0x0a, 0x04, 0x64, 0x61, 0x74,
	0x61, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1e, 0x2e, 0x6d, 0x61, 0x69, 0x6e, 0x2e, 0x50,
	0x6f, 0x73, 0x74, 0x4d, 0x65, 0x64, 0x69, 0x61, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x22, 0xe1, 0x01,
	0x0a, 0x18, 0x50, 0x6f, 0x73, 0x74, 0x4d, 0x65, 0x64, 0x69, 0x61, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x17, 0x0a, 0x07, 0x66, 0x69,
	0x6c, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x66, 0x69, 0x6c,
	0x65, 0x49, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x66, 0x69, 0x6c, 0x65, 0x6e, 0x61, 0x6d, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x66, 0x69, 0x6c, 0x65, 0x6e, 0x61, 0x6d, 0x65, 0x12,
	0x1d, 0x0a, 0x0a, 0x75, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x5f, 0x75, 0x72, 0x6c, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x09, 0x75, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x55, 0x72, 0x6c, 0x12, 0x21,
	0x0a, 0x0c, 0x73, 0x74, 0x6f, 0x72, 0x61, 0x67, 0x65, 0x5f, 0x70, 0x61, 0x74, 0x68, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x73, 0x74, 0x6f, 0x72, 0x61, 0x67, 0x65, 0x50, 0x61, 0x74,
	0x68, 0x12, 0x29, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x05, 0x20, 0x01, 0x28,
	0x0e, 0x32, 0x11, 0x2e, 0x6d, 0x61, 0x69, 0x6e, 0x2e, 0x4d, 0x65, 0x64, 0x69, 0x61, 0x53, 0x74,
	0x61, 0x74, 0x75, 0x73, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x23, 0x0a, 0x0d,
	0x65, 0x72, 0x72, 0x6f, 0x72, 0x5f, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x06, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x0c, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x22, 0x43, 0x0a, 0x0f, 0x47, 0x65, 0x74, 0x4d, 0x65, 0x64, 0x69, 0x61, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x30, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x1c, 0x2e, 0x6d, 0x61, 0x69, 0x6e, 0x2e, 0x47, 0x65, 0x74, 0x4d, 0x65, 0x64,
	0x69, 0x61, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x22, 0x31, 0x0a, 0x16, 0x47, 0x65, 0x74, 0x4d, 0x65, 0x64,
	0x69, 0x61, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x12, 0x17, 0x0a, 0x07, 0x66, 0x69, 0x6c, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x06, 0x66, 0x69, 0x6c, 0x65, 0x49, 0x64, 0x22, 0x45, 0x0a, 0x10, 0x47, 0x65, 0x74,
	0x4d, 0x65, 0x64, 0x69, 0x61, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x31, 0x0a,
	0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1d, 0x2e, 0x6d, 0x61,
	0x69, 0x6e, 0x2e, 0x47, 0x65, 0x74, 0x4d, 0x65, 0x64, 0x69, 0x61, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61,
	0x22, 0xa0, 0x02, 0x0a, 0x17, 0x47, 0x65, 0x74, 0x4d, 0x65, 0x64, 0x69, 0x61, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x21, 0x0a, 0x0c,
	0x64, 0x6f, 0x77, 0x6e, 0x6c, 0x6f, 0x61, 0x64, 0x5f, 0x75, 0x72, 0x6c, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x0b, 0x64, 0x6f, 0x77, 0x6e, 0x6c, 0x6f, 0x61, 0x64, 0x55, 0x72, 0x6c, 0x12,
	0x17, 0x0a, 0x07, 0x66, 0x69, 0x6c, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x06, 0x66, 0x69, 0x6c, 0x65, 0x49, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x66, 0x69, 0x6c, 0x65,
	0x6e, 0x61, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x66, 0x69, 0x6c, 0x65,
	0x6e, 0x61, 0x6d, 0x65, 0x12, 0x1b, 0x0a, 0x09, 0x6d, 0x69, 0x6d, 0x65, 0x5f, 0x74, 0x79, 0x70,
	0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x6d, 0x69, 0x6d, 0x65, 0x54, 0x79, 0x70,
	0x65, 0x12, 0x1d, 0x0a, 0x0a, 0x73, 0x69, 0x7a, 0x65, 0x5f, 0x62, 0x79, 0x74, 0x65, 0x73, 0x18,
	0x05, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x73, 0x69, 0x7a, 0x65, 0x42, 0x79, 0x74, 0x65, 0x73,
	0x12, 0x1f, 0x0a, 0x0b, 0x75, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x65, 0x64, 0x5f, 0x61, 0x74, 0x18,
	0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x75, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x65, 0x64, 0x41,
	0x74, 0x12, 0x2b, 0x0a, 0x04, 0x6d, 0x65, 0x74, 0x61, 0x18, 0x07, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x17, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75,
	0x66, 0x2e, 0x53, 0x74, 0x72, 0x75, 0x63, 0x74, 0x52, 0x04, 0x6d, 0x65, 0x74, 0x61, 0x12, 0x23,
	0x0a, 0x0d, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x5f, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18,
	0x08, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x4d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x2a, 0x3f, 0x0a, 0x0b, 0x4d, 0x65, 0x64, 0x69, 0x61, 0x53, 0x74, 0x61, 0x74,
	0x75, 0x73, 0x12, 0x0c, 0x0a, 0x08, 0x4d, 0x45, 0x44, 0x49, 0x41, 0x5f, 0x4f, 0x4b, 0x10, 0x00,
	0x12, 0x0f, 0x0a, 0x0b, 0x4d, 0x45, 0x44, 0x49, 0x41, 0x5f, 0x45, 0x52, 0x52, 0x4f, 0x52, 0x10,
	0x01, 0x12, 0x11, 0x0a, 0x0d, 0x4d, 0x45, 0x44, 0x49, 0x41, 0x5f, 0x53, 0x4b, 0x49, 0x50, 0x50,
	0x45, 0x44, 0x10, 0x02, 0x32, 0x7e, 0x0a, 0x05, 0x4d, 0x65, 0x64, 0x69, 0x61, 0x12, 0x3b, 0x0a,
	0x08, 0x50, 0x6f, 0x73, 0x74, 0x55, 0x52, 0x4c, 0x73, 0x12, 0x16, 0x2e, 0x6d, 0x61, 0x69, 0x6e,
	0x2e, 0x50, 0x6f, 0x73, 0x74, 0x4d, 0x65, 0x64, 0x69, 0x61, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x17, 0x2e, 0x6d, 0x61, 0x69, 0x6e, 0x2e, 0x50, 0x6f, 0x73, 0x74, 0x4d, 0x65, 0x64,
	0x69, 0x61, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x38, 0x0a, 0x07, 0x47, 0x65,
	0x74, 0x55, 0x52, 0x4c, 0x73, 0x12, 0x15, 0x2e, 0x6d, 0x61, 0x69, 0x6e, 0x2e, 0x47, 0x65, 0x74,
	0x4d, 0x65, 0x64, 0x69, 0x61, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x16, 0x2e, 0x6d,
	0x61, 0x69, 0x6e, 0x2e, 0x47, 0x65, 0x74, 0x4d, 0x65, 0x64, 0x69, 0x61, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x42, 0x3b, 0x5a, 0x39, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63,
	0x6f, 0x6d, 0x2f, 0x73, 0x65, 0x62, 0x61, 0x73, 0x74, 0x74, 0x69, 0x61, 0x6e, 0x6f, 0x31, 0x33,
	0x2f, 0x41, 0x6e, 0x6e, 0x69, 0x65, 0x44, 0x61, 0x64, 0x2f, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e,
	0x61, 0x6c, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x61, 0x6e, 0x6e, 0x69, 0x65, 0x64, 0x61,
	0x64, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_internal_proto_anniedad_anniedad_proto_rawDescOnce sync.Once
	file_internal_proto_anniedad_anniedad_proto_rawDescData = file_internal_proto_anniedad_anniedad_proto_rawDesc
)

func file_internal_proto_anniedad_anniedad_proto_rawDescGZIP() []byte {
	file_internal_proto_anniedad_anniedad_proto_rawDescOnce.Do(func() {
		file_internal_proto_anniedad_anniedad_proto_rawDescData = protoimpl.X.CompressGZIP(file_internal_proto_anniedad_anniedad_proto_rawDescData)
	})
	return file_internal_proto_anniedad_anniedad_proto_rawDescData
}

var file_internal_proto_anniedad_anniedad_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_internal_proto_anniedad_anniedad_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_internal_proto_anniedad_anniedad_proto_goTypes = []interface{}{
	(MediaStatus)(0),                 // 0: main.MediaStatus
	(*PostMediaRequest)(nil),         // 1: main.PostMediaRequest
	(*PostMediaRequestMessage)(nil),  // 2: main.PostMediaRequestMessage
	(*PostMediaResponse)(nil),        // 3: main.PostMediaResponse
	(*PostMediaResponseMessage)(nil), // 4: main.PostMediaResponseMessage
	(*GetMediaRequest)(nil),          // 5: main.GetMediaRequest
	(*GetMediaRequestMessage)(nil),   // 6: main.GetMediaRequestMessage
	(*GetMediaResponse)(nil),         // 7: main.GetMediaResponse
	(*GetMediaResponseMessage)(nil),  // 8: main.GetMediaResponseMessage
	(*structpb.Struct)(nil),          // 9: google.protobuf.Struct
}
var file_internal_proto_anniedad_anniedad_proto_depIdxs = []int32{
	2, // 0: main.PostMediaRequest.data:type_name -> main.PostMediaRequestMessage
	9, // 1: main.PostMediaRequestMessage.meta:type_name -> google.protobuf.Struct
	4, // 2: main.PostMediaResponse.data:type_name -> main.PostMediaResponseMessage
	0, // 3: main.PostMediaResponseMessage.status:type_name -> main.MediaStatus
	6, // 4: main.GetMediaRequest.data:type_name -> main.GetMediaRequestMessage
	8, // 5: main.GetMediaResponse.data:type_name -> main.GetMediaResponseMessage
	9, // 6: main.GetMediaResponseMessage.meta:type_name -> google.protobuf.Struct
	1, // 7: main.Media.PostURLs:input_type -> main.PostMediaRequest
	5, // 8: main.Media.GetURLs:input_type -> main.GetMediaRequest
	3, // 9: main.Media.PostURLs:output_type -> main.PostMediaResponse
	7, // 10: main.Media.GetURLs:output_type -> main.GetMediaResponse
	9, // [9:11] is the sub-list for method output_type
	7, // [7:9] is the sub-list for method input_type
	7, // [7:7] is the sub-list for extension type_name
	7, // [7:7] is the sub-list for extension extendee
	0, // [0:7] is the sub-list for field type_name
}

func init() { file_internal_proto_anniedad_anniedad_proto_init() }
func file_internal_proto_anniedad_anniedad_proto_init() {
	if File_internal_proto_anniedad_anniedad_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_internal_proto_anniedad_anniedad_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PostMediaRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_proto_anniedad_anniedad_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PostMediaRequestMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_proto_anniedad_anniedad_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PostMediaResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_proto_anniedad_anniedad_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PostMediaResponseMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_proto_anniedad_anniedad_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetMediaRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_proto_anniedad_anniedad_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetMediaRequestMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_proto_anniedad_anniedad_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetMediaResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_proto_anniedad_anniedad_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetMediaResponseMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_internal_proto_anniedad_anniedad_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_proto_anniedad_anniedad_proto_goTypes,
		DependencyIndexes: file_internal_proto_anniedad_anniedad_proto_depIdxs,
		EnumInfos:         file_internal_proto_anniedad_anniedad_proto_enumTypes,
		MessageInfos:      file_internal_proto_anniedad_anniedad_proto_msgTypes,
	}.Build()
	File_internal_proto_anniedad_anniedad_proto = out.File
	file_internal_proto_anniedad_anniedad_proto_rawDesc = nil
	file_internal_proto_anniedad_anniedad_proto_goTypes = nil
	file_internal_proto_anniedad_anniedad_proto_depIdxs = nil
}
