// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.1
// 	protoc        v5.26.1
// source: internal/proto/anniedad/anniedad.proto

package anniedad

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PostMediaRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Filename string `protobuf:"bytes,1,opt,name=filename,proto3" json:"filename,omitempty"`
}

func (x *PostMediaRequest) Reset() {
	*x = PostMediaRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_proto_anniedad_anniedad_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PostMediaRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PostMediaRequest) ProtoMessage() {}

func (x *PostMediaRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_anniedad_anniedad_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PostMediaRequest.ProtoReflect.Descriptor instead.
func (*PostMediaRequest) Descriptor() ([]byte, []int) {
	return file_internal_proto_anniedad_anniedad_proto_rawDescGZIP(), []int{0}
}

func (x *PostMediaRequest) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

type PostMediaResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Url string `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
}

func (x *PostMediaResponse) Reset() {
	*x = PostMediaResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_proto_anniedad_anniedad_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PostMediaResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PostMediaResponse) ProtoMessage() {}

func (x *PostMediaResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_anniedad_anniedad_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PostMediaResponse.ProtoReflect.Descriptor instead.
func (*PostMediaResponse) Descriptor() ([]byte, []int) {
	return file_internal_proto_anniedad_anniedad_proto_rawDescGZIP(), []int{1}
}

func (x *PostMediaResponse) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

type GetMediaRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Filename string `protobuf:"bytes,1,opt,name=filename,proto3" json:"filename,omitempty"`
}

func (x *GetMediaRequest) Reset() {
	*x = GetMediaRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_proto_anniedad_anniedad_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetMediaRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMediaRequest) ProtoMessage() {}

func (x *GetMediaRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_anniedad_anniedad_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMediaRequest.ProtoReflect.Descriptor instead.
func (*GetMediaRequest) Descriptor() ([]byte, []int) {
	return file_internal_proto_anniedad_anniedad_proto_rawDescGZIP(), []int{2}
}

func (x *GetMediaRequest) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

type GetMediaResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Url string `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
}

func (x *GetMediaResponse) Reset() {
	*x = GetMediaResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_proto_anniedad_anniedad_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetMediaResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMediaResponse) ProtoMessage() {}

func (x *GetMediaResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_anniedad_anniedad_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMediaResponse.ProtoReflect.Descriptor instead.
func (*GetMediaResponse) Descriptor() ([]byte, []int) {
	return file_internal_proto_anniedad_anniedad_proto_rawDescGZIP(), []int{3}
}

func (x *GetMediaResponse) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

type GetListURLResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Url []string `protobuf:"bytes,1,rep,name=url,proto3" json:"url,omitempty"`
}

func (x *GetListURLResponse) Reset() {
	*x = GetListURLResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_proto_anniedad_anniedad_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetListURLResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetListURLResponse) ProtoMessage() {}

func (x *GetListURLResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_anniedad_anniedad_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetListURLResponse.ProtoReflect.Descriptor instead.
func (*GetListURLResponse) Descriptor() ([]byte, []int) {
	return file_internal_proto_anniedad_anniedad_proto_rawDescGZIP(), []int{4}
}

func (x *GetListURLResponse) GetUrl() []string {
	if x != nil {
		return x.Url
	}
	return nil
}

var File_internal_proto_anniedad_anniedad_proto protoreflect.FileDescriptor

var file_internal_proto_anniedad_anniedad_proto_rawDesc = []byte{
	0x0a, 0x26, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x2f, 0x61, 0x6e, 0x6e, 0x69, 0x65, 0x64, 0x61, 0x64, 0x2f, 0x61, 0x6e, 0x6e, 0x69, 0x65, 0x64,
	0x61, 0x64, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x04, 0x6d, 0x61, 0x69, 0x6e, 0x1a, 0x1b,
	0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f,
	0x65, 0x6d, 0x70, 0x74, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x2e, 0x0a, 0x10, 0x50,
	0x6f, 0x73, 0x74, 0x4d, 0x65, 0x64, 0x69, 0x61, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x1a, 0x0a, 0x08, 0x66, 0x69, 0x6c, 0x65, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x08, 0x66, 0x69, 0x6c, 0x65, 0x6e, 0x61, 0x6d, 0x65, 0x22, 0x25, 0x0a, 0x11, 0x50,
	0x6f, 0x73, 0x74, 0x4d, 0x65, 0x64, 0x69, 0x61, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x10, 0x0a, 0x03, 0x75, 0x72, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x75,
	0x72, 0x6c, 0x22, 0x2d, 0x0a, 0x0f, 0x47, 0x65, 0x74, 0x4d, 0x65, 0x64, 0x69, 0x61, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x66, 0x69, 0x6c, 0x65, 0x6e, 0x61, 0x6d,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x66, 0x69, 0x6c, 0x65, 0x6e, 0x61, 0x6d,
	0x65, 0x22, 0x24, 0x0a, 0x10, 0x47, 0x65, 0x74, 0x4d, 0x65, 0x64, 0x69, 0x61, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x72, 0x6c, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x03, 0x75, 0x72, 0x6c, 0x22, 0x26, 0x0a, 0x12, 0x47, 0x65, 0x74, 0x4c, 0x69,
	0x73, 0x74, 0x55, 0x52, 0x4c, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x10, 0x0a,
	0x03, 0x75, 0x72, 0x6c, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x03, 0x75, 0x72, 0x6c, 0x32,
	0xba, 0x01, 0x0a, 0x05, 0x4d, 0x65, 0x64, 0x69, 0x61, 0x12, 0x3a, 0x0a, 0x07, 0x50, 0x6f, 0x73,
	0x74, 0x55, 0x52, 0x4c, 0x12, 0x16, 0x2e, 0x6d, 0x61, 0x69, 0x6e, 0x2e, 0x50, 0x6f, 0x73, 0x74,
	0x4d, 0x65, 0x64, 0x69, 0x61, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x17, 0x2e, 0x6d,
	0x61, 0x69, 0x6e, 0x2e, 0x50, 0x6f, 0x73, 0x74, 0x4d, 0x65, 0x64, 0x69, 0x61, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x37, 0x0a, 0x06, 0x47, 0x65, 0x74, 0x55, 0x52, 0x4c, 0x12,
	0x15, 0x2e, 0x6d, 0x61, 0x69, 0x6e, 0x2e, 0x47, 0x65, 0x74, 0x4d, 0x65, 0x64, 0x69, 0x61, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x16, 0x2e, 0x6d, 0x61, 0x69, 0x6e, 0x2e, 0x47, 0x65,
	0x74, 0x4d, 0x65, 0x64, 0x69, 0x61, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x3c,
	0x0a, 0x0a, 0x47, 0x65, 0x74, 0x4c, 0x69, 0x73, 0x74, 0x55, 0x52, 0x4c, 0x12, 0x16, 0x2e, 0x67,
	0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45,
	0x6d, 0x70, 0x74, 0x79, 0x1a, 0x16, 0x2e, 0x6d, 0x61, 0x69, 0x6e, 0x2e, 0x47, 0x65, 0x74, 0x4d,
	0x65, 0x64, 0x69, 0x61, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x3b, 0x5a, 0x39,
	0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x73, 0x65, 0x62, 0x61, 0x73,
	0x74, 0x74, 0x69, 0x61, 0x6e, 0x6f, 0x31, 0x33, 0x2f, 0x41, 0x6e, 0x6e, 0x69, 0x65, 0x44, 0x61,
	0x64, 0x2f, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x2f, 0x61, 0x6e, 0x6e, 0x69, 0x65, 0x64, 0x61, 0x64, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_internal_proto_anniedad_anniedad_proto_rawDescOnce sync.Once
	file_internal_proto_anniedad_anniedad_proto_rawDescData = file_internal_proto_anniedad_anniedad_proto_rawDesc
)

func file_internal_proto_anniedad_anniedad_proto_rawDescGZIP() []byte {
	file_internal_proto_anniedad_anniedad_proto_rawDescOnce.Do(func() {
		file_internal_proto_anniedad_anniedad_proto_rawDescData = protoimpl.X.CompressGZIP(file_internal_proto_anniedad_anniedad_proto_rawDescData)
	})
	return file_internal_proto_anniedad_anniedad_proto_rawDescData
}

var file_internal_proto_anniedad_anniedad_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_internal_proto_anniedad_anniedad_proto_goTypes = []interface{}{
	(*PostMediaRequest)(nil),   // 0: main.PostMediaRequest
	(*PostMediaResponse)(nil),  // 1: main.PostMediaResponse
	(*GetMediaRequest)(nil),    // 2: main.GetMediaRequest
	(*GetMediaResponse)(nil),   // 3: main.GetMediaResponse
	(*GetListURLResponse)(nil), // 4: main.GetListURLResponse
	(*emptypb.Empty)(nil),      // 5: google.protobuf.Empty
}
var file_internal_proto_anniedad_anniedad_proto_depIdxs = []int32{
	0, // 0: main.Media.PostURL:input_type -> main.PostMediaRequest
	2, // 1: main.Media.GetURL:input_type -> main.GetMediaRequest
	5, // 2: main.Media.GetListURL:input_type -> google.protobuf.Empty
	1, // 3: main.Media.PostURL:output_type -> main.PostMediaResponse
	3, // 4: main.Media.GetURL:output_type -> main.GetMediaResponse
	3, // 5: main.Media.GetListURL:output_type -> main.GetMediaResponse
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_internal_proto_anniedad_anniedad_proto_init() }
func file_internal_proto_anniedad_anniedad_proto_init() {
	if File_internal_proto_anniedad_anniedad_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_internal_proto_anniedad_anniedad_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PostMediaRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_proto_anniedad_anniedad_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PostMediaResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_proto_anniedad_anniedad_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetMediaRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_proto_anniedad_anniedad_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetMediaResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_proto_anniedad_anniedad_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetListURLResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_internal_proto_anniedad_anniedad_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_proto_anniedad_anniedad_proto_goTypes,
		DependencyIndexes: file_internal_proto_anniedad_anniedad_proto_depIdxs,
		MessageInfos:      file_internal_proto_anniedad_anniedad_proto_msgTypes,
	}.Build()
	File_internal_proto_anniedad_anniedad_proto = out.File
	file_internal_proto_anniedad_anniedad_proto_rawDesc = nil
	file_internal_proto_anniedad_anniedad_proto_goTypes = nil
	file_internal_proto_anniedad_anniedad_proto_depIdxs = nil
}
